name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # Inject your API key securely from GitHub secrets.
      ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install CMake
        uses: lukka/get-cmake@v3.31.6

      - name: Install dependencies via vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh
          ./vcpkg install cpr nlohmann-json
          cd ..
        shell: bash

      - name: Create/Clear Build Directory
        run: |
          if [ -d build ]; then
            rm -rf build
          fi
          mkdir build
        shell: bash

      - name: Configure and Build with CMake
        run: |
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake ..
          cmake --build .
        shell: bash

      # Uncomment to run tests
      # - name: Run Tests
      #   run: |
      #     cd build
      #     ./arbitrage-sports-betting
      #   shell: bash
