name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # You can trigger on other events as needed

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # This will be injected from your GitHub secrets.
      ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: lukka/get-cmake@v3

      - name: Install dependencies via vcpkg
        run: |
          # Clone vcpkg (or you can set up your project to use vcpkg in a different way)
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh
          ./vcpkg install cpr nlohmann-json
          cd ..
        shell: bash

      - name: Configure and Build with CMake
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake ..
          cmake --build .
        shell: bash

      # - name: Run Tests
      #   run: |
      #     cd build
      #     ./arbitrage-sports-betting
      #   shell: bash
